name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "your-database-name"		#d1数据库名字
database_id = "your-database-id-here"		#d1数据库id

[[kv_namespaces]]
binding = "kv"			#kv绑定名默认不可修改
id = "your-kv-namespace-id"					#kv数据库id
preview_id = "your-kv-preview-id"			#kv预览数据库id

[[r2_buckets]]
binding = "r2"			#r2对象存储绑定名默认不可修改
bucket_name = "your-r2-bucket-name"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行

# 自定义域名配置（可选）
[[routes]]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

[vars]
orm_log = false
domain = ["your-email-domain.com"]				#邮件域名配置
admin = "admin@your-email-domain.com"			#管理员的邮箱
jwt_secret = "your-random-jwt-secret-string-here"	#jwt令牌的密钥,请修改为随机字符串
# OAuth 配置（可选，如果需要 Linux.do OAuth 登录）
# LINUX_DO_CLIENT_ID = "your-client-id"
# LINUX_DO_CLIENT_SECRET = "your-client-secret"
# 大学链接配置（可选，如果需要在页面显示大学链接）
# UNIVERSITY_URL = "https://your-university.edu"
# UNIVERSITY_NAME = "Your University Name"

